# Generated by Django 3.2.9 on 2021-11-26 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinin',
            name='fileupload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files'),
            preserve_default=False,
        ),
    ]
