# Generated by Django 3.2.9 on 2021-11-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinin_fileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinin',
            new_name='Clinic',
        ),
    ]
